version: 2
jobs:
  build:
    docker:
        - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: ls
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: push to master
          command: |
              git config --global user.name "morimolymoly"
              git config --global user.email "morimolymoly@gmail.com"
              
