version: 2
jobs:
  build:
    docker:
        - image: cibuilds/hugo:latest
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: config
          command: |
              apk update && apk add git
              HUGO_ENV=production hugo -v
              git config --global user.name "morimolymoly"
              git config --global user.email "morimolymoly@gmail.com"

      - run:
          name: push to master
          command: |
              git clone https://github.com/morimolymoly/leetcode-blog --recursive
              hugo
              cp -rp public/* github.io/
              cd github.io
              ls
              git remote set-url origin git@github.com:morimolymoly/leetcode-blog
              git add .
              git commit -m "[ci skip] publish"
              git push origin master
